version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      spring:
        patterns:
          - "org.springframework*"
      testing:
        patterns:
          - "*junit*"
          - "*mockito*"
          - "*assertj*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
